//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test_thoithiet.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("test_thoithiet.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;err&quot;: 0,
        ///  &quot;msg&quot;: &quot;Success&quot;,
        ///  &quot;data&quot;: {
        ///    &quot;boards&quot;: [
        ///      {
        ///        &quot;boardId&quot;: &quot;hanoi&quot;,
        ///        &quot;displayName&quot;: &quot;Hà Nội&quot;,
        ///        &quot;latitude&quot;: &quot;21.028167&quot;,
        ///        &quot;longitude&quot;: &quot;105.854152&quot;,
        ///        &quot;entries&quot;: [
        ///          {
        ///            &quot;status&quot;: &quot;Mây rải rác&quot;,
        ///            &quot;iconCode&quot;: 34,
        ///            &quot;iconUrl&quot;: &quot;https://baomoi-static.zadn.vn/infoservice/images/weathericons/set61/34.svg&quot;
        ///          }
        ///        ]
        ///      },
        ///      {
        ///        &quot;boardId&quot;: &quot;tphochiminh&quot;,
        ///        &quot;displayName&quot;: [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string thoi_tiet {
            get {
                return ResourceManager.GetString("thoi_tiet", resourceCulture);
            }
        }
    }
}
